---
name: sakuramai
version: 3

libraries: 
- name: django 
  version: '1.6.1' 

handlers: 
- url: /static 
  static_dir: static 

- url: /favicon2013.ico
  static_path: favicon2013.ico

- url: /favicon2014.ico
  static_path: favicon2014.ico

- url: /static/
  gzip: on
